Repository openshift/ocm-container, pull requests merged in 2023-07, with the labels that each got.

#172 Adds optional PersonalizationFile config
  README.md
  env.source.sample
  ocm-container.sh
  utils/bashrc.d/99-personalizations.bashrc
Labels: approved, lgtm, lifecycle/stale

#186 Update rosa cli to latest
  Dockerfile
Labels: approved, lgtm

#188 [OCPBUGS-14550] Update cluster-console image
  utils/bin/cluster-console
Labels: approved, lgtm

#189 Add k9s utility
  Dockerfile
Labels: approved, lgtm

#190 Google repo el9, enable gpg check
  utils/dockerfile_assets/google-cloud-sdk.repo
Labels: approved, lgtm

#187 Add Backplane dependencies for bp-cli 0.1.7
  Dockerfile
  ocm-container.sh
  utils/bin/sre-login
  utils/dockerfile_assets/containers.conf
  utils/dockerfile_assets/storage.conf
Labels: approved, lgtm

#191 Fix the prompt when using new backplane
  utils/bashrc.d/06-sre-utils.bashrc
Labels: approved, lgtm

#192 adds missing fi statements
  ocm-container.sh
Labels: approved, lgtm

#196 no reason to exit when doing a build with missing env.source config, …
  build.sh
Labels: approved, lgtm

#198 set CONTAINER_SUBSYS to podman
  env.source.sample
Labels: approved, lgtm

#201 backplane bump to v0.1.8
  Dockerfile
Labels: approved, lgtm

#197 Adds check for SSH_AUTH_SOCK
  ocm-container.sh
Labels: approved, lgtm

#200 Autodetect container subsystem
  build.sh
  env.source.sample
Labels: approved, lgtm

#202 add build targers for ci build
  Dockerfile
  Makefile
Labels: approved, tide/merge-method-squash, lgtm

#194 Add bash completion for the new backplane
  Dockerfile
Labels: approved, lgtm

#203 Handle sha prefix
  Makefile
Labels: approved, lgtm

#204 Fix makefile typo
  Makefile
Labels: approved, lgtm

#206 Update OSDCTL to v0.17.0
  Dockerfile
Labels: approved, lgtm
